// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface CloudflareBindings {
  CLOUDFLARE_SECRET_ACCESS_KEY: string;
  CLOUDFLARE_ACCESS_KEY_ID: string;
  CLOUDFLARE_ACCOUNT_ID: string;
  CLOUDFLARE_ACCESS_TOKEN: string;
}
